### ISSUE TITLE
Battery drain while sleeping

### ISSUE THREAD

**Issue by stuarthayhurst** [tomsom/yoga-linux#8]
Sorry if this is the wrong place, but it's difficult to find Linux users with this laptop. Does anyone know roughly what the battery drain of this laptop while sleeping is, out of the box? I know there are some issues around S3 sleep, but I can't find any reliable information on how bad the situation actually is with battery drain.

Thanks!

**Comment by tomsom** [comment]
Hey, of course you are allowed to ask here :)
As far as I know S3 doesnt work cause its not supported by lenovo/in the BIOS.
Though since kernel 6.1 s2idle(S0) sleep is supported and works quite well:
I left the system(fedora 36) idling 10h over night and lost ~3% battery.
So it wont last for weeks but it also wont die in your backpack over the day

**Comment by stuarthayhurst** [comment]
Oh good, thank you :)
